import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Box, Flex, Heading, Text, VStack } from '@chakra-ui/react'
import axios from 'axios'
import { useEffect, useState } from 'react'
import RenderBox from '@/components/RenderBox'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Longform Preview</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Flex w="100%" dir="row" align="center" justify="center" wrap="wrap" margin="10">
          {Array(10).fill().map((_, i) => <RenderBox key={i} seed={i} />)}
      </Flex>
    </>
  )
}

/*export function getServerSideProps() {

}*/